### ISSUE TITLE
Update Installation Documentation for Concourse v1.0.0 and up

### ISSUE THREAD

**Issue by mattrothenberg** [starkandwayne/slack-notification-resource-boshrelease#12]
This is a very helpful resource, thanks for the hard work.

I just finished installing it on a Concourse 1.2.0 deployment, and noticed one discrepancy between the installation docs, and how the Concourse 1.0.0+ deployment manifests expects jobs to be structured. 

**In your docs**, you include the `slack-notification-resource` under the `jobs.templates` key, e.g:

```
jobs:
- name: worker
  templates:
    ...
    - {release: slack-notification-resource, name: slack-notification-resource}
```

But I believe Concourse expects said release as an additional `job` underneath the `worker` instance group.

```
- name: worker
  instances: 1
  vm_type: worker
  stemcell: trusty
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: slack-notification-resource
    release: slack-notification-resource
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-linux
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
```

Hope this is correct / offers some guidance to folks trying to get set up on Concourse 1.0.0.

Matt
